# This will run a provisioned docker container on your machine from a docker image.
Vagrant.configure(2) do |config|
    config.vm.provider "docker" do |d|
        d.image = "tknerr/baseimage-ubuntu:18.04"
        d.has_ssh = true
        d.name = "jeffs-ubuntu-container"
    end
    
    # use shell and other provisioners as usual
    config.vm.provision "shell", inline: "sudo apt-get install htop"
end

# Once you have the image you can
# docker exec -i -t jeffs-ubuntu-container /bin/bash
# vagrant docker-exec -it -- /bin/sh
