# This will create a virtualbox vm on your machine from a vagrant box.
Vagrant.configure(2) do |jeffsconfig|
  
    # STEP 1 - GET BASE BOX ########################################################

    jeffsconfig.vm.box = "concourse/lite"
    jeffsconfig.vm.box_version = "3.2.1"

    # STEP 2 - CONFIGURE ON PROVIDER (WINDOWS VIRTUALBOX) ##########################
    
    # Don't use shared mount folder (You would need guest additions to do this)    
    jeffsconfig.vm.synced_folder '.', '/vagrant', disabled: true

    # Will not created .ssh key pairs.
    # You can use insecure public key you already placed in ~/.ssh/authorized_keys
    # This is so we can ssh with another ssh client using
    # vagrant insecure private keys ~/.vagrant.d/insecure_private_key
    jeffsconfig.ssh.insert_key = false 
    jeffsconfig.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']

    jeffsconfig.vm.provider "virtualbox" do |jeffsvb|
        jeffsvb.name = 'concourse-lite-321-vm'
        jeffsvb.gui = true  # turn on the graphic window
        jeffsvb.memory = 2048
        jeffsvb.cpus = 2
        jeffsvb.customize ["modifyvm", :id, "--groups", "/From Vagrant Up"]
        jeffsvb.customize ["modifyvm", :id, "--vram", "128"] 
        # jeffsvb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        # jeffsvb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    # STEP 3 - PROVISION ###########################################################

    jeffsconfig.vm.provision "shell", inline: <<-SHELL
        # apt-get update
        # sudo apt-get install -y htop
    SHELL
  
end