# This will create a virtualbox vm on your machine from a vagrant box.
Vagrant.configure(2) do |jeffsconfig|
  
    # STEP 1 - GET BASE BOX
    jeffsconfig.vm.box = "ubuntu/xenial64"

    # STEP 2 - CONFIGURE ON PROVIDER (WINDOWS VIRTUALBOX)

    # Place the vagrant insecure public key in ~/.ssh/authorized_keys
    # This is so we can ssh with another ssh client using
    # vagrant insecure private keys ~/.vagrant.d/insecure_private_key
    jeffsconfig.ssh.insert_key = false 

    jeffsconfig.vm.provider "virtualbox" do |jeffsvb|
        jeffsvb.name = 'ubuntu-1604-virtualbox-vm'
        # turn on the graphic window
        jeffsvb.gui = true  
        jeffsvb.memory = 8192
        jeffsvb.cpus = 2
        jeffsvb.customize ["modifyvm", :id, "--groups", "/From Vagrant Up"]
        jeffsvb.customize ["modifyvm", :id, "--vram", "128"] 
        # jeffsvb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        # jeffsvb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    # STEP 3 - PROVISION
    jeffsconfig.vm.provision "shell", inline: <<-SHELL
        apt-get update
        sudo apt-get install -y htop
    SHELL
  
end
